#outline what to do with travis-ci
#1. Tell Travis we need a copy of Doccker running
#2. Build out image using Dockerfile.dev
#3. Tell Travis how to run our test suite
#4. Tell Travis how to deploy our code to AWS
#---------------------------------------------
sudo: required
services:
  - docker

before_install:
  - docker build -t bkmearoy/docker-webapp -f Dockerfile.dev .

script:
  - docker run -e CI=true bkmearoy/docker-webapp npm run test
